name: Waka Readme

on:
  # Run the workflow at 12 AM and 12 PM UTC (5:30 AM and 5:30 PM IST)
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Customize the blocks used for the stats graph
          BLOCKS: ⚫◼▣█
